### ISSUE TITLE
How to add resources directory to the robot-server

### ISSUE THREAD

**Issue by ericof** [plone/plone.themepreview#1]
Is there any way to use resource directories (https://pypi.python.org/pypi/plone.resource) to host themes using robot-server?

**Comment by datakurre** [comment]
@ericof  Is the resource directory configured only in the buildout and theme activated manually from p.a.theming controlpanel?

I think, this requires a new feature for the special test layer in p.a.robotframework. If you could provide an example, I could make it work. (Technically it should be only about registering the directory and configuring the theme. It could be done in your own test layer, but I could add that support for the reusable layer in p.a.robotframework.)

**Comment by datakurre** [comment]
@ericof Ping. (I miss typed your username for the first time and I'm not sure, did you get a notification for this.)
